version: '3.3'
services:
  frontend:
    build:
      context: .
    ports:
      - 3000:3000
    env_file: /.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes: 
      - .:/app
      - /app/node_modules